### ISSUE TITLE
Quoting in calls of texosquery fails

### ISSUE THREAD

**Issue by eg9** [nlct/texosquery#5]
Setup: TeX Live 2017 pretest on Mac OS X 10.11 (no MacTeX); modified `texosquery.cfg` for enabling restricted shell escape and to use JRE8

Test file:

    \input texosquery

    \TeXOSQuery{\result}{-i ; .}
    {\tt\meaning\result}

    \TeXOSQuery{\result}{-i \string\noexpand\string\\ .}
    {\tt\meaning\result}

    \let\\\par\result

    \bye

Output:

<img width="382" alt="screen shot 2017-04-22 at 11 19 49" src="https://cloud.githubusercontent.com/assets/302839/25303169/a53428fa-274d-11e7-87e4-18e42f5b1b40.png">

Second test:

The example in the documentation

    \input texosquery

    \TeXOSQueryFileList{\result}{\string\noexpand\string\\}{.}

    {\tt\meaning\result}

    \bye

results in

    This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=pdftex)
     restricted \write18 enabled.
    entering extended mode
    (./test.tex
    (/usr/local/texlive/2017/texmf-dist/tex/latex/texosquery/texosquery.tex
    
    TeXOSQuery: reading configuration file
    (./texosquery.cfg))
    runpopen quotation error in command line: texosquery-jre8 -i '\noexpand\\' '.' 
    
    ! I can't find file `"|texosquery-jre8 -i '\noexpand\\' '.' "'.
    \TeXOSQueryInvoker ...TeXOSInvokerName \space #1" 
                                                      
    \TeXOSQuery ...noexpand #1{\TeXOSQueryInvoker {#2}
                                                      }}\x \fi 
    l.3 ...List{\result}{\string\noexpand\string\\}{.}
                                                      ^^M
    (Press Enter to retry, or Control-D to exit)
    Please type another input file name:

**Comment by nlct** [comment]
It works fine with the unrestricted mode, so it seems to be a problem with the restricted mode. It doesn't just occur with `texosquery`. The follow generates a similar error in restricted mode:
```tex
{\tt\input"|bibtex '-v'" }
\bye
```
Similarly with `\write18`:
```tex
\immediate\write18{bibtex '-v'}
Test.
\bye
```
Works fine in unrestricted mode, but in restricted mode this causes:
```
runsystem(bibtex '-v')...quotation error in system command.
```

**Comment by nlct** [comment]
I've had confirmation that this is a security feature of the restricted mode which prohibits the single quote character in the shell escape. To allow for this, v1.4 has changed the shortcut commands so that they only delimit the arguments with single quotes in unrestricted mode. If any arguments contain any spaces or other problematic characters, the unrestricted mode will have to be used.
